name: Download all file
on:
  push:
    branches:
      - main
jobs:
  build-and-download:
    runs-on: ubuntu-latest
    steps:
    - name: get
      run: |
        npm i 
        node main.js
          
          
  
