name: Download all file
on:
  push:
    branches:
      - main
jobs:
  build-and-download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install and Build
      run: |
        npm install
        npm run-script build
    - uses: actions/download-artifact@v2
      with:
        path: 'build'
