name: Download all file
on:
  push:
    branches:
      - main
jobs:
  build-and-download:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: get
        run: |
          npm i systeminformation
          node get.js
          
          
  
