name: Download all file
on:
  push:
    branches:
      - main
jobs:
  build-and-download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: src
        path: |
          @(src/*svg|src/*css)
          
          
  
